module.exports = {
    // HTML5 form types
    TYPE_CHECKBOX: 'checkbox',
    TYPE_SELECT: 'select',
    TYPE_RADIO: 'radio',
    TYPE_TEXT: 'text',
    TYPE_FILE: 'file',
    TYPE_TEXTAREA: 'textarea',
    TYPE_HIDDEN: 'hidden',
    TYPE_EMAIL: 'email',
    TYPE_PASSWORD: 'password',
    TYPE_COLOR: 'color',
    TYPE_DATE: 'date',
    TYPE_DATETIME: 'datetime',
    TYPE_NUMBER: 'number',
    TYPE_RANGE: 'range',
    TYPE_SEARCH: 'search',
    TYPE_TIME: 'time',
    TYPE_TEL: 'tel',
    TYPE_URL: 'url',
    TYPE_MONTH: 'month',
    TYPE_WEEK: 'week',
    TYPE_SLIDER: 'slider',
    // actions
    ACTION_CREATE: 'create',
    ACTION_EDIT: 'edit',
    ACTION_DELETE: 'delete',
    ACTION_RELOAD: 'reload',
    // buttons
    EDITOR_CREATE: 'editor_create',
    EDITOR_EDIT: 'editor_edit',
    EDITOR_REMOVE: 'editor_remove',
    EDITOR_CSV: 'editor_csv',
    EDITOR_RELOAD: 'editor_reload',
    // different opts
    EXTENDED: 'extended',
    // http methods
    HTTP_METHOD_POST: 'POST',
    HTTP_METHOD_PUT: 'PUT',
    HTTP_METHOD_DELETE: 'DELETE',

    EDITABLE_CELLS_INDEX: 'editable-cells',
    PLUGINS_RTE: 'rte',
    PLUGINS_RC_SLIDER: 'rc-slider',
    PLUGINS_RC_RANGE: 'rc-slider',
};
