module.exports = {
  'en': {
      'gte_editor_popupheader_delete': 'Delete',
      'gte_editor_popupheader_edit': 'Edit',
      'gte_editor_popupheader_create': 'Create row',
      'gte_editor_sendbtn_create': 'Create',
      'gte_editor_sendbtn_update': 'Update',
      'gte_editor_sendbtn_delete': 'Delete',
      'show': 'Show',
      'entries': 'entries',
      'no_entries': 'No entries',
      'showing': 'Showing',
      'to': 'to',
      'of': 'of',
      'prev': 'Previous',
      'next': 'Next',
      'search': 'Search',
      'editor_create': 'New',
      'editor_edit': 'Edit',
      'editor_remove': 'Delete',
      'editor_csv': 'CSV Export',
      'editor_reload': 'Reload',
      'gte_editor_delete_popup': 'Are You sure You wish to delete {{rows}} row(s)?',
      'gte_editor_multiple_rows': 'note: multiple rows mode - changed fields will be sent for selected rows'
  },
  'gr': {
      'gte_editor_popupheader_delete': 'Löschen',
      'gte_editor_popupheader_edit': 'Bearbeiten',
      'gte_editor_popupheader_create': 'Neu zeile',
      'gte_editor_sendbtn_create': 'Erstellen',
      'gte_editor_sendbtn_update': 'Aktualisieren',
      'gte_editor_sendbtn_delete': 'Löschen',
      'show': 'Zeigen',
      'entries': 'einträge',
      'no_entries': 'Keine einträge',
      'showing': 'Zeigen',
      'to': 'bis',
      'of': 'von',
      'prev': 'früher',
      'next': 'Nächste',
      'search': 'Suche',
      'editor_create': 'Neu',
      'editor_edit': 'Bearbeiten',
      'editor_remove': 'Löschen',
      'editor_csv': 'CSV Export',
      'editor_reload': 'Neu laden',
      'gte_editor_delete_popup': 'Sind Sie sicher, dass Sie {{rows}} Zeile(n) löschen möchten?',
      'gte_editor_multiple_rows': 'Hinweis: Modus für mehrere Zeilen - geänderte Felder werden für ausgewählte Zeilen gesendet'
  },
  'ru': {
      'gte_editor_popupheader_delete': 'Удалить',
      'gte_editor_popupheader_edit': 'Редактировать',
      'gte_editor_popupheader_create': 'Создать строку',
      'gte_editor_sendbtn_create': 'Создать',
      'gte_editor_sendbtn_update': 'Сохранить',
      'gte_editor_sendbtn_delete': 'Удвлить',
      'show': 'Показать',
      'entries': 'строк',
      'no_entries': 'Нет записей',
      'showing': 'Показано от',
      'to': 'до',
      'of': 'из',
      'prev': 'Пред.',
      'next': 'След.',
      'search': 'Поиск',
      'editor_create': 'Создать',
      'editor_edit': 'Редактировать',
      'editor_remove': 'Удалить',
      'editor_csv': 'CSV выгрузка',
      'editor_reload': 'Перезагрузить',
      'gte_editor_delete_popup': 'Вы уверены, что хотите удалить {{rows}} строк(и)?',
      'gte_editor_multiple_rows': 'внимание: режим редактирования нескольких строк - измененные поля будут отправлены для выбранных строк'
  },
  'fr': {
      'gte_editor_popupheader_delete': 'Effacer',
      'gte_editor_popupheader_edit': 'éditer',
      'gte_editor_popupheader_create': 'Créer rangée',
      'gte_editor_sendbtn_create': 'Créer',
      'gte_editor_sendbtn_update': 'Réactualiser',
      'gte_editor_sendbtn_delete': 'Effacer',
      'show': 'Montrer',
      'entries': 'entrées',
      'no_entries': 'Aucune entrée',
      'showing': 'Projection',
      'to': 'à',
      'of': 'de',
      'prev': 'Précédent',
      'next': 'Suivant',
      'search': 'Recherche',
      'editor_create': 'Créer',
      'editor_edit': 'éditer',
      'editor_remove': 'Effacer',
      'editor_csv': 'CSV Export',
      'editor_reload': 'Recharger',
      'gte_editor_delete_popup': 'Êtes-vous sûr de vouloir supprimer {{rows}} ligne(s)?',
      'gte_editor_multiple_rows': 'Remarque: Mode multi-lignes - les champs modifiés sont envoyés pour les lignes sélectionnées'
  },
  'es': {
      'gte_editor_popupheader_delete': 'Borrar',
      'gte_editor_popupheader_edit': 'Editar',
      'gte_editor_popupheader_create': 'Crear fila',
      'gte_editor_sendbtn_create': 'Crear',
      'gte_editor_sendbtn_update': 'Actualizar',
      'gte_editor_sendbtn_delete': 'Borrar',
      'show': 'Mostrar',
      'entries': 'Entradas',
      'no_entries': 'No entrar',
      'showing': 'Demostración',
      'to': 'a',
      'of': 'de',
      'prev': 'Anterior',
      'next': 'Próximo',
      'search': 'Buscar',
      'editor_create': 'Crear',
      'editor_edit': 'Editar',
      'editor_remove': 'Borrar',
      'editor_csv': 'CSV Export',
      'editor_reload': 'Recargar',
      'gte_editor_delete_popup': 'Estás seguro de que deseas eliminar {{rows}} fila(s)?',
      'gte_editor_multiple_rows': 'Nota: modo de múltiples filas - los campos modificados se envían para las filas seleccionadas'
  },
  'ch': {
      'gte_editor_popupheader_delete': '删除',
      'gte_editor_popupheader_edit': '修改',
      'gte_editor_popupheader_create': '新增',
      'gte_editor_sendbtn_create': '创建',
      'gte_editor_sendbtn_update': '更新',
      'gte_editor_sendbtn_delete': '删除',
      'show': '显示',
      'entries': '条数据',
      'no_entries': '没有条目',
      'showing': '显示',
      'to': '至',
      'of': '的',
      'prev': '前一页',
      'next': '后一页',
      'search': '查找',
      'editor_create': '新增',
      'editor_edit': '修改',
      'editor_remove': '删除',
      'editor_csv': 'CSV Export',
      'editor_reload': '刷新',
      'gte_editor_delete_popup': '您确定要删除{{rows}}行吗？',
      'gte_editor_multiple_rows': '提示：多行模式-修改后的字段将应用于所有已选数据'
  },
  'hi': {
      'gte_editor_popupheader_delete': 'हटाना',
      'gte_editor_popupheader_edit': 'संपादन करना',
      'gte_editor_popupheader_create': 'पंक्ति बना',
      'gte_editor_sendbtn_create': 'सृजना',
      'gte_editor_sendbtn_update': 'अद्यतन करें',
      'gte_editor_sendbtn_delete': 'हटाना',
      'show': 'प्रदर्शन',
      'entries': 'आइटम',
      'no_entries': 'कोई प्रविष्टि नहीं',
      'showing': 'नुमाइश',
      'to': 'तक',
      'of': 'की',
      'prev': 'पूर्व',
      'next': 'अगला',
      'search': 'खोज',
      'editor_create': 'बनाना',
      'editor_edit': 'संपादन करना',
      'editor_remove': 'हटाना',
      'editor_csv': 'CSV Export',
      'editor_reload': 'सीमा से अधिक लादना',
      'gte_editor_delete_popup': 'क्या आप वाकई {{rows}} पंक्तियां हटाना चाहते हैं?',
      'gte_editor_multiple_rows': 'नोट: मल्टी-पंक्ति मोड - चयनित पंक्तियों के लिए संशोधित फ़ील्ड भेजे जाते हैं'
  }
};
