module.exports = {
  'en': {
      'gte_editor_popupheader_delete': 'Delete',
      'gte_editor_popupheader_edit': 'Edit',
      'gte_editor_popupheader_create': 'Create row',
      'gte_editor_sendbtn_create': 'Create',
      'gte_editor_sendbtn_update': 'Update',
      'gte_editor_sendbtn_delete': 'Delete',
      'show': 'Show',
      'entries': 'entries',
      'showing': 'Showing',
      'to': 'to',
      'of': 'of',
      'prev': 'Previous',
      'next': 'Next',
      'search': 'Search',
      'editor_create': 'New',
      'editor_edit': 'Edit',
      'editor_remove': 'Delete',
      'gte_editor_delete_popup': 'Are You sure You wish to delete {{rows}} row(s)?',
  },
  'gr': {
      'gte_editor_popupheader_delete': 'Löschen',
      'gte_editor_popupheader_edit': 'Bearbeiten',
      'gte_editor_popupheader_create': 'Neu zeile',
      'gte_editor_sendbtn_create': 'Erstellen',
      'gte_editor_sendbtn_update': 'Aktualisieren',
      'gte_editor_sendbtn_delete': 'Löschen',
      'show': 'Zeigen',
      'entries': 'einträge',
      'showing': 'Zeigen',
      'to': 'bis',
      'of': 'von',
      'prev': 'früher',
      'next': 'Nächste',
      'search': 'Suche',
      'editor_create': 'Neu',
      'editor_edit': 'Bearbeiten',
      'editor_remove': 'Löschen',
      'gte_editor_delete_popup': 'Sind Sie sicher, dass Sie {{rows}} Zeile(n) löschen möchten?',
  },
  'ru': {
      'gte_editor_popupheader_delete': 'Удалить',
      'gte_editor_popupheader_edit': 'Редактировать',
      'gte_editor_popupheader_create': 'Создать строку',
      'gte_editor_sendbtn_create': 'Создать',
      'gte_editor_sendbtn_update': 'Сохранить',
      'gte_editor_sendbtn_delete': 'Удвлить',
      'show': 'Показать',
      'entries': 'строк',
      'showing': 'Показано от',
      'to': 'до',
      'of': 'из',
      'prev': 'Пред.',
      'next': 'След.',
      'search': 'Поиск',
      'editor_create': 'Создать',
      'editor_edit': 'Редактировать',
      'editor_remove': 'Удалить',
      'gte_editor_delete_popup': 'Вы уверены, что хотите удалить {{rows}} строк(и)?',
  },
  'fr': {
      'gte_editor_popupheader_delete': 'Effacer',
      'gte_editor_popupheader_edit': 'éditer',
      'gte_editor_popupheader_create': 'Créer rangée',
      'gte_editor_sendbtn_create': 'Créer',
      'gte_editor_sendbtn_update': 'Réactualiser',
      'gte_editor_sendbtn_delete': 'Effacer',
      'show': 'Montrer',
      'entries': 'entrées',
      'showing': 'Projection',
      'to': 'à',
      'of': 'de',
      'prev': 'Précédent',
      'next': 'Suivant',
      'search': 'Recherche',
      'editor_create': 'Créer',
      'editor_edit': 'éditer',
      'editor_remove': 'Effacer',
      'gte_editor_delete_popup': 'Êtes-vous sûr de vouloir supprimer {{rows}} ligne(s)?',
  },
  'es': {
      'gte_editor_popupheader_delete': 'Borrar',
      'gte_editor_popupheader_edit': 'Editar',
      'gte_editor_popupheader_create': 'Crear fila',
      'gte_editor_sendbtn_create': 'Crear',
      'gte_editor_sendbtn_update': 'Actualizar',
      'gte_editor_sendbtn_delete': 'Borrar',
      'show': 'Mostrar',
      'entries': 'Entradas',
      'showing': 'Demostración',
      'to': 'a',
      'of': 'de',
      'prev': 'Anterior',
      'next': 'Próximo',
      'search': 'Buscar',
      'editor_create': 'Crear',
      'editor_edit': 'Editar',
      'editor_remove': 'Borrar',
      'gte_editor_delete_popup': 'Estás seguro de que deseas eliminar {{rows}} fila(s)?',
  },
  'ch': {
      'gte_editor_popupheader_delete': '删除',
      'gte_editor_popupheader_edit': '修改',
      'gte_editor_popupheader_create': '新增',
      'gte_editor_sendbtn_create': '创建',
      'gte_editor_sendbtn_update': '更新',
      'gte_editor_sendbtn_delete': '删除',
      'show': '显示',
      'entries': '条数据',
      'showing': '显示',
      'to': '至',
      'of': '的',
      'prev': '前一页',
      'next': '后一页',
      'search': '查找',
      'editor_create': '新增',
      'editor_edit': '修改',
      'editor_remove': '删除',
      'gte_editor_delete_popup': '您确定要删除{{rows}}行吗？',
  },
  'hi': {
      'gte_editor_popupheader_delete': 'हटाना',
      'gte_editor_popupheader_edit': 'संपादन करना',
      'gte_editor_popupheader_create': 'पंक्ति बना',
      'gte_editor_sendbtn_create': 'सृजना',
      'gte_editor_sendbtn_update': 'अद्यतन करें',
      'gte_editor_sendbtn_delete': 'हटाना',
      'show': 'प्रदर्शन',
      'entries': 'आइटम',
      'showing': 'नुमाइश',
      'to': 'तक',
      'of': 'की',
      'prev': 'पूर्व',
      'next': 'अगला',
      'search': 'खोज',
      'editor_create': 'बनाना',
      'editor_edit': 'संपादन करना',
      'editor_remove': 'हटाना',
      'gte_editor_delete_popup': 'क्या आप वाकई {{rows}} पंक्तियां हटाना चाहते हैं?',
  }
};
